### ISSUE TITLE
require "etna" fails

### ISSUE THREAD

**Issue by kukushkin-sb** [solarisBank/etna#3]
Requiring "etna" somewhere fails, because `Forwardable` is not defined. See example below.

Gemfile:
```ruby
source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "etna", github: "solarisBank/etna"
```

Gemfile.lock:
```
GIT
  remote: https://github.com/solarisBank/etna
  revision: 8386a396bf99d204d69321f8e4b0f57fab099290
  specs:
    etna (0.1.0)
      json
      typhoeus

GEM
  remote: https://rubygems.org/
  specs:
    ethon (0.12.0)
      ffi (>= 1.3.0)
    ffi (1.11.1)
    json (2.2.0)
    typhoeus (1.3.1)
      ethon (>= 0.9.0)

PLATFORMS
  ruby

DEPENDENCIES
  etna!

BUNDLED WITH
   2.0.2
```

test.rb:
```
require "etna"
```

Running `bundle exec ruby test.rb` fails with the following:
```
Traceback (most recent call last):
	9: from test.rb:1:in `<main>'
	8: from test.rb:1:in `require'
	7: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna.rb:8:in `<top (required)>'
	6: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna.rb:8:in `glob'
	5: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna.rb:8:in `block in <top (required)>'
	4: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna.rb:8:in `require'
	3: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna/components/response.rb:3:in `<top (required)>'
	2: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna/components/response.rb:4:in `<module:Etna>'
	1: from /var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna/components/response.rb:6:in `<module:Components>'
/var/lib/gems/2.6.0/bundler/gems/etna-8386a396bf99/lib/etna/components/response.rb:7:in `<class:Response>': uninitialized constant Etna::Components::Response::Forwardable (NameError)
```

**Comment by josetonyp** [comment]
Solving it on [PR 4](https://github.com/solarisBank/etna/pull/4).

**Comment by josetonyp** [comment]
Solved on previously mentioned PR
